- hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip
  vars:
    ansible_host: "{{ hostvars[inventory_hostname]['bigiq_host'] }}"
    ansible_user: admin
    ansible_httpapi_password: "{{ hostvars[inventory_hostname]['bigiq_password'] }}"
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.f5_bigip.bigiq
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
  tasks:
    - name: Revoke BIG-IP License
      bigiq_utility_license_assignment:
        device: "{{ inventory_hostname }}"
        device_username: admin
        device_password: "{{ hostvars[inventory_hostname]['password'] }}"
        managed: no
        key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX
        offering: "{{ hostvars[inventory_hostname]['offering'] }}"
        unit_of_measure: yearly
        state: absent
