- hosts: all
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip
  vars:
    ansible_host: 10.1.1.4
    ansible_user: admin
    ansible_httpapi_password: f5bigiqadmin
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.f5_bigip.bigiq
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
  tasks:
    - name: License BIG-IP
      bigiq_utility_license_assignment:
        device: 10.1.1.6
        device_username: admin
        device_password: "!f5admin"
        managed: no
        key: XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX
        offering: F5-BIG-MSP-AWF-1G-LIC-DEV
        unit_of_measure: yearly
